---
apiVersion: "v1"
kind: "ConfigMap"
metadata:
    name: "core-device-api-config"
    namespace: "default"
    labels:
        app: "core-device-api"
data:
    DeviceDatabaseSettings__ConnectionString: "{DATABASE_CONNECTION_STRING}"
    ASPNETCORE_ENVIRONMENT: "{ENVIRONMENT}"
    Serilog__Properties__Environment: "{ENVIRONMENT}"
    Serilog__Properties__Application: "core-device-api"
    Serilog__Properties__BuildNumber: "{BUILD_NUMBER}"
    Serilog__WriteTo__0__Args__projectId: "{PROJECT_ID}"
---
apiVersion: "apps/v1"
kind: "Deployment"
metadata:
    name: "core-device-api"
    namespace: "default"
    labels:
        app: "core-device-api"
spec:
    replicas: 1
    selector:
        matchLabels:
            app: "core-device-api"
    template:
        metadata:
            labels:
                app: "core-device-api"
        spec:
            containers:
                -   name: "core-device-api"
                    image: "gcr.io/production-282111/core-device-api:{BUILD_NUMBER}"
                    ports:
                        -   containerPort: 80
                            protocol: TCP
                    env:
                        -   name: "ASPNETCORE_ENVIRONMENT"
                            valueFrom:
                                configMapKeyRef:
                                    key: "ASPNETCORE_ENVIRONMENT"
                                    name: "core-device-api-config"
                        -   name: "DeviceDatabaseSettings__ConnectionString"
                            valueFrom:
                                configMapKeyRef:
                                    key: "DeviceDatabaseSettings__ConnectionString"
                                    name: "core-device-api-config"
                        -   name: "Serilog__WriteTo__0__Args__projectId"
                            valueFrom:
                                configMapKeyRef:
                                    key: "Serilog__WriteTo__0__Args__projectId"
                                    name: "core-device-api-config"
                        -   name: "Serilog__Properties__Application"
                            valueFrom:
                                configMapKeyRef:
                                    key: "Serilog__Properties__Application"
                                    name: "core-device-api-config"
                        -   name: "Serilog__Properties__BuildNumber"
                            valueFrom:
                                configMapKeyRef:
                                    key: "Serilog__Properties__BuildNumber"
                                    name: "core-device-api-config"
                        -   name: "Serilog__Properties__Environment"
                            valueFrom:
                                configMapKeyRef:
                                    key: "Serilog__Properties__Environment"
                                    name: "core-device-api-config"
---
apiVersion: "autoscaling/v2beta1"
kind: "HorizontalPodAutoscaler"
metadata:
    name: "core-device-api-hpa-sd9s"
    namespace: "default"
    labels:
        app: "core-device-api"
spec:
    scaleTargetRef:
        kind: "Deployment"
        name: "core-device-api"
        apiVersion: "apps/v1"
    minReplicas: 1
    maxReplicas: 5
    metrics:
        -   type: "Resource"
            resource:
                name: "cpu"
                targetAverageUtilization: 80
---
apiVersion: "v1"
kind: "Service"
metadata:
    name: "core-device-api-service"
    namespace: "default"
    labels:
        app: "core-device-api"
spec:
    ports:
        -   name: "8080-to-80-tcp"
            protocol: TCP
            port: 8080
            targetPort: 80
            nodePort: 30000
    selector:
        app: "core-device-api"
    type: "NodePort"
---
apiVersion: "networking.gke.io/v1beta2"
kind: "ManagedCertificate"
metadata:
    name: "api-certificate"
spec:
    domains:
        -   device.thoud.co
---
apiVersion: "networking.k8s.io/v1beta1"
kind: "Ingress"
metadata:
    name: "api-ingress"
    namespace: "default"
    annotations:
        networking.gke.io/managed-certificates: "api-certificate"
spec:
    rules:
        -   host: "device.thoud.co"
            http:
                paths:
                    -   backend:
                            serviceName: "core-device-api-service"
                            servicePort: 8080
